pyworxcloud/__init__.py

There should be no logic changes, only checking if data to read exists in json.
After PR this needs to be reuploaded as python lib

Update json data checks

---

pyworxcloud/utils/actions.py

Fixes #47 
Will need new landroid_cloud release as well

Set zone now using the correct attribute

---

pyworxcloud/utils/actions.py

Set_mowingzone-fails-again-issue54

---

pyworxcloud/utils/mqtt.py

Fixes #60 - will require update of landroid_cloud integration as well.

Adding missing char from regex checking on the data syntax

---

pyworxcloud/__init__.py
pyworxcloud/utils/actions.py
pyworxcloud/utils/zone.py

And introduce a check to see if the requested zone is actually defined or not.

Fix incorrect zone mapping on setzone

---

pyworxcloud/__init__.py
pyworxcloud/utils/devices.py
pyworxcloud/utils/mqtt.py

Fixing MQTT information mismatch

---

pyworxcloud/__init__.py
pyworxcloud/utils/devices.py
pyworxcloud/utils/mqtt.py

Default the timezone to UTC if no time_zone attr was found in device data

---

pyworxcloud/api.py
pyworxcloud/clouds.py

Should make Aldi Ferrex integration working now

Refactor authentication

---

pyworxcloud/__init__.py
pyworxcloud/api.py
pyworxcloud/clouds.py

This should allow for Worx Landroid devices to work again

Fix token generation for Worx Landroid devices

---

.vscode/settings.json
pyworxcloud/utils/mqtt.py

Switch from 0 (at most one) to 1 (at least one) on the QoS settings

Update QoS flag

---

pyworxcloud/utils/devices.py
pyworxcloud/utils/schedules.py

mapping was not working for auto_schedule 
I think there is the same issue with lawn but I didn't test yet that part

fix auto_schedule mapping

---

pyproject.toml
pyworxcloud/__init__.py

Fix wrong Python requirement

---

pyworxcloud/exceptions.py
pyworxcloud/utils/requests.py

Fix-timeout-handling

---

pyworxcloud/__init__.py

Only set raw_data if last_status is not None

---

pyworxcloud/utils/zone.py

Adding check for data in last_status

---

poetry.lock
pyproject.toml

Home Assistant cannot handle requests 2.31.0 yet

Downgrade requests requirement

---

pyworxcloud/api.py

Remove float conversion for firmware

---

pyworxcloud/__init__.py

Dataset was marked invalid because Kress doesn't present serial number in the same way as Landroid

Fixing dataset matching for Kress

---

pyworxcloud/__init__.py

Fixes https://github.com/MTrab/landroid_cloud/issues/556

Send device home when enabling party_mode

---

pyworxcloud/__init__.py

Fixes https://github.com/MTrab/landroid_cloud/issues/561

Reverting the home command on enabling partymode

---

pyworxcloud/utils/requests.py
test.py
test2.py

Related to debugging in https://github.com/MTrab/landroid_cloud/issues/538

Add backoff to error 429

---

pyworxcloud/__init__.py

Related to https://github.com/MTrab/landroid_cloud/issues/580

Fix invalid zone detection

---

pyworxcloud/__init__.py
pyworxcloud/api.py
pyworxcloud/utils/requests.py

Attempt to better handle error 429, regarding this issue: https://github.com/MTrab/landroid_cloud/issues/538

Better handling of 429 errors

---

pyworxcloud/utils/capability.py

Relates to https://github.com/MTrab/landroid_cloud/issues/584

Fix capability check for OTS and EdgeCut

---

pyworxcloud/__init__.py

The bug was introduced by commit 9a88283.
This fixes https://github.com/MTrab/landroid_cloud/issues/585

Fixed broken zone existance check

---

pyworxcloud/__init__.py

Fix missing GPS data exception

---

pyworxcloud/utils/devices.py

Fix incorrect protocol mapping

---

pyworxcloud/api.py
pyworxcloud/utils/mqtt.py

Fix token refresh resulting in temporary IP ban

---

pyworxcloud/utils/mqtt.py

Fixing await publish

---

pyworxcloud/utils/blades.py

Fix typo resulting in TypeError on blade reset

---

pyproject.toml
pyworxcloud/__init__.py
pyworxcloud/utils/mqtt.py
test_async.py

Refactor waiting for connection to MQTT endpoint

---

pyworxcloud/__init__.py

This is not needed and could potentially cause a MQTT ban

Remove forced MQTT refresh

---

pyworxcloud/__init__.py
pyworxcloud/exceptions.py
pyworxcloud/utils/capability.py

Add cutting height functions

---

pyworxcloud/__init__.py
pyworxcloud/utils/devices.py

Provides a fix for https://github.com/MTrab/landroid_cloud/issues/928

Fix party mode on newer models
